import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { Id } from "./_generated/dataModel";
import { getOrCreateSpendingWallet } from "./utils/walletHelpers";

export const getWallets = query({
  args: { accountId: v.id("accounts") },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Not authenticated");
    }

    const account = await ctx.db.get(args.accountId);
    if (!account) {
      throw new Error("Account not found");
    }

    const user = await ctx.db
      .query("users")
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
      .first();
    
    if (!user || account.userId !== user._id) {
      throw new Error("Not authorized to access this account");
    }

    return await ctx.db
      .query("wallets")
      .withIndex("by_account_id", (q) => q.eq("accountId", args.accountId))
      .collect();
  },
});

export const createWallet = mutation({
  args: {
    accountId: v.id("accounts"),
    type: v.union(v.literal("spending"), v.literal("savings"), v.literal("multisig")),
    name: v.string(),
    username: v.string(),
    multisigConfig: v.optional(v.object({
      requiredSignatures: v.number(),
      signers: v.array(v.object({
        pubKey: v.string(),
        weight: v.number(),
      })),
      scriptType: v.union(v.literal("p2sh"), v.literal("p2wsh"), v.literal("p2tr")),
    })),
  },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Not authenticated");
    }

    const account = await ctx.db.get(args.accountId);
    if (!account) {
      throw new Error("Account not found");
    }

    const user = await ctx.db
      .query("users")
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
      .first();
    
    if (!user || account.userId !== user._id) {
      throw new Error("Not authorized to access this account");
    }

    const networkIdentities = (() => {
      switch (args.type) {
        case "spending":
          return {
            type: "spending" as const,
            lightning: `${args.username}@bitchat.com`,
            nostr: `${args.username}@bitchat.com`,
          };
        case "savings":
          return {
            type: "savings" as const,
            bitcoinAddress: `bc1q...`, // Generate or get from external service
            derivationPath: "m/84'/0'/0'/0/0", // Example path
          };
        case "multisig":
          if (!args.multisigConfig) {
            throw new Error("Multisig configuration required for multisig wallet");
          }
          
          const { requiredSignatures, signers, scriptType } = args.multisigConfig;
          
          // Create the multisig setup
          const multisigSetup = {
            type: "multisig" as const,
            addresses: [{
              address: "", // Will be generated by wallet service
              signers,
              requiredSignatures,
            }],
            scriptType,
          };
          
          // Validate the setup
          validateMultisigSetup(multisigSetup.addresses);
          
          return multisigSetup;
      }
    })();

    return await ctx.db.insert("wallets", {
      accountId: args.accountId,
      type: args.type,
      name: args.name,
      balance: 0,
      currency: "sats",
      lastUpdated: new Date().toISOString(),
      networkIdentities,
    });
  },
});

export const updateBalance = mutation({
  args: {
    walletId: v.id("wallets"),
    amount: v.number(),
    type: v.union(v.literal("credit"), v.literal("debit")),
  },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Not authenticated");
    }

    const wallet = await ctx.db.get(args.walletId);
    if (!wallet) {
      throw new Error("Wallet not found");
    }

    const account = await ctx.db.get(wallet.accountId);
    if (!account) {
      throw new Error("Account not found");
    }

    const user = await ctx.db
      .query("users")
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
      .first();
    
    if (!user || account.userId !== user._id) {
      throw new Error("Not authorized to access this wallet");
    }

    const newBalance = args.type === "credit" 
      ? wallet.balance + args.amount 
      : wallet.balance - args.amount;

    if (newBalance < 0) {
      throw new Error("Insufficient balance");
    }

    return await ctx.db.patch(args.walletId, {
      balance: newBalance,
      lastUpdated: new Date().toISOString(),
    });
  },
});

export const getWalletsByAccounts = query({
  args: { 
    accountIds: v.array(v.id("accounts"))
  },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Not authenticated");
    }

    if (args.accountIds.length === 0) {
      return [];
    }

    return await ctx.db
      .query("wallets")
      .withIndex("by_account_id")
      .filter(q => 
        args.accountIds.some(accountId => 
          q.eq(q.field("accountId"), accountId)
        )
      )
      .collect();
  },
});

export const importWallet = mutation({
  args: {
    accountId: v.id("accounts"), // Using Convex account ID
    type: v.union(v.literal("spending"), v.literal("savings"), v.literal("multisig")),
    name: v.string(),
    balance: v.number(),
    currency: v.string(),
    lastUpdated: v.string(),
    networkIdentities: v.union(
      v.object({
        type: v.literal("spending"),
        lightning: v.string(),
        nostr: v.string(),
      }),
      v.object({
        type: v.literal("savings"),
        bitcoinAddress: v.string(),
        derivationPath: v.string(),
      }),
      v.object({
        type: v.literal("multisig"),
        addresses: v.array(v.object({
          address: v.string(),
          signers: v.array(v.object({
            pubKey: v.string(),
            weight: v.number(),
          })),
          requiredSignatures: v.number(),
        })),
        scriptType: v.union(v.literal("p2sh"), v.literal("p2wsh"), v.literal("p2tr")),
      })
    ),
  },
  handler: async (ctx, args) => {
    return await ctx.db.insert("wallets", args);
  },
});

export interface SpendingWalletInput {
  type: "spending";
  lightning: string;
  nostr: string;
}

export interface SavingsWalletInput {
  type: "savings";
  bitcoinAddress: string;
  derivationPath: string;
}

export interface MultisigWalletInput {
  type: "multisig";
  addresses: Array<{
    address: string;
    signers: Array<{
      pubKey: string;
      weight: number;
    }>;
    requiredSignatures: number;
  }>;
  scriptType: "p2sh" | "p2wsh" | "p2tr";
}

type WalletNetworkIdentities = SpendingWalletInput | SavingsWalletInput | MultisigWalletInput;

export const addWallet = mutation({
  args: {
    accountId: v.id("accounts"),
    name: v.string(),
    type: v.union(v.literal("spending"), v.literal("savings"), v.literal("multisig")),
    currency: v.string(),
    networkIdentities: v.union(
      v.object({
        type: v.literal("spending"),
        lightning: v.string(),
        nostr: v.string(),
      }),
      v.object({
        type: v.literal("savings"),
        bitcoinAddress: v.string(),
        derivationPath: v.string(),
      }),
      v.object({
        type: v.literal("multisig"),
        addresses: v.array(v.object({
          address: v.string(),
          signers: v.array(v.object({
            pubKey: v.string(),
            weight: v.number(),
          })),
          requiredSignatures: v.number(),
        })),
        scriptType: v.union(
          v.literal("p2sh"),
          v.literal("p2wsh"),
          v.literal("p2tr")
        ),
      })
    ),
  },
  handler: async (ctx, args) => {
    // Validate account exists
    const account = await ctx.db.get(args.accountId);
    if (!account) {
      throw new Error("Account not found");
    }

    // Validate network identities match wallet type
    if (args.type !== args.networkIdentities.type) {
      throw new Error("Network identities type must match wallet type");
    }

    // Add multisig validation
    if (args.type === "multisig") {
      validateMultisigSetup(args.networkIdentities.addresses);
    }

    // Create the wallet
    const walletId = await ctx.db.insert("wallets", {
      accountId: args.accountId,
      name: args.name,
      type: args.type,
      balance: 0, // New wallets start with 0 balance
      currency: args.currency,
      lastUpdated: new Date().toISOString(),
      networkIdentities: args.networkIdentities,
    });

    return walletId;
  },
});

// Helper mutation for updating wallet balance
export const updateWalletBalance = mutation({
  args: {
    walletId: v.id("wallets"),
    balance: v.number(),
  },
  handler: async (ctx, args) => {
    const wallet = await ctx.db.get(args.walletId);
    if (!wallet) {
      throw new Error("Wallet not found");
    }

    await ctx.db.patch(args.walletId, {
      balance: args.balance,
      lastUpdated: new Date().toISOString(),
    });

    return args.walletId;
  },
});

// Helper mutation for updating wallet name
export const updateWalletName = mutation({
  args: {
    walletId: v.id("wallets"),
    name: v.string(),
  },
  handler: async (ctx, args) => {
    const wallet = await ctx.db.get(args.walletId);
    if (!wallet) {
      throw new Error("Wallet not found");
    }

    await ctx.db.patch(args.walletId, {
      name: args.name,
      lastUpdated: new Date().toISOString(),
    });

    return args.walletId;
  },
});

// Add these validation utilities
function validateMultisigSetup(
  addresses: Array<{
    signers: Array<{ weight: number }>;
    requiredSignatures: number;
  }>
) {
  for (const address of addresses) {
    const totalWeight = address.signers.reduce((sum, signer) => sum + signer.weight, 0);
    if (totalWeight < address.requiredSignatures) {
      throw new Error(
        `Invalid multisig setup: total weight (${totalWeight}) must be >= required signatures (${address.requiredSignatures})`
      );
    }
    if (address.signers.length < 2) {
      throw new Error("Multisig wallet requires at least 2 signers");
    }
  }
}

export const getCurrentUserSpendingWallet = query({
  args: {},
  handler: async (ctx) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Not authenticated");
    }

    // Get user by clerk ID
    const user = await ctx.db
      .query("users")
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", identity.subject))
      .first();

    if (!user) {
      throw new Error("User not found");
    }

    // Find user's personal account and spending wallet
    const account = await ctx.db
      .query("accounts")
      .withIndex("by_user_and_type", (q) => 
        q.eq("userId", user._id).eq("type", "personal")
      )
      .first();

    if (!account) {
      throw new Error("Account not found");
    }

    // Get spending wallet
    const wallet = await ctx.db
      .query("wallets")
      .withIndex("by_account_and_type", (q) =>
        q.eq("accountId", account._id).eq("type", "spending")
      )
      .first();

    if (!wallet) {
      throw new Error("Spending wallet not found");
    }

    return wallet;
  },
}); 
